### PR TITLE
Update README.md for first use case

### PR DESCRIPTION
**Pull request by nihaopaul**
an extra step for the first out of box experience required for nrf52, took me a few hours to test why the following did not work:
```
void setup() {
  pinMode(PIN_LED1, OUTPUT);
  pinMode(PIN_LED2, OUTPUT);
  pinMode(PIN_LED3, OUTPUT);
  pinMode(PIN_LED4, OUTPUT);
}

void loop() {
  digitalWrite(PIN_LED1, HIGH);
  delay(50);
  digitalWrite(PIN_LED2, HIGH);
  delay(50);
  digitalWrite(PIN_LED3, HIGH);
  delay(50);
  digitalWrite(PIN_LED4, HIGH);
  delay(50);
  digitalWrite(PIN_LED1, LOW);
  delay(50);
  digitalWrite(PIN_LED2, LOW);
  delay(50);
  digitalWrite(PIN_LED3, LOW);
  delay(50);
  digitalWrite(PIN_LED4, LOW);
  delay(50);
}
```

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@nihaopaul thank you!

I've reworded slightly in https://github.com/sandeepmistry/arduino-nRF5/commit/0d9988f0cb9dc970ba2fa9a61574e98408c76ebf.

Just curious, when did you get your board? What does it say on the sticker? Mine says:

```
PCA10040
V1.0.0
2016.9
```

**Comment by nihaopaul** [comment]
@sandeepmistry the sticker has the following: 

```
PCA10040 
v0.9.0 
2015.44 
```

both @saurabhdatta and i have the same ones.

**Comment by prjh** [comment]
```
PA10040
V1.1.0
2016.11
```
is my variant and out of the box working.

**Comment by sandeepmistry** [comment]
@nihaopaul @prjh thank for the info! I've added a note for this in https://github.com/sandeepmistry/arduino-nRF5/commit/4cc0744b0f0720c64e13ac02a811857adb829d8f.

**Pull request merged**
