### PR TITLE
Add RedBear Blend 2 variant

### PR DESCRIPTION
**Pull request by sandeepmistry**
Based on the nRF52DK variant.

@dlabun whenever you have a few minutes could you please review? If things look good please merge, thanks.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Sorry, hold off for now, there's something wrong with the Serial port.

**Comment by sandeepmistry** [comment]
Ok, updated the serial pins, good to go now!

**Comment by dlabun** [comment]
Looks good to me

**Comment by sandeepmistry** [comment]
@dlabun cool, thanks for reviewing!

**Pull request merged**
