### PR TITLE
disable DMA I2C on BLE Nano 2

### PR DESCRIPTION
**Pull request by gtalusan**
This will at least get I2C working on the RedBear BLE Nano 2.

I don't have any different boards for which this is a problem, so I'm assuming Wire_nRF52 is working for everything else except the Nano 2.

### CODE REVIEW

**Comment by dlabun** [comment]
This is the first I am hearing about a problem with the BLE Nano 2 having I2C issues, are you sure it's related to the I2C library?

**Comment by gtalusan** [comment]
Whoops, my bad.  That's what I get for reading the world news in another tab.  Updated the commit.

#108 and #199 talk about problems with I2C on the nRF52.  At the moment I'd like to just get I2C working with this core.

I2C works with the RedBearLabs core, but it doesn't use DMA either.

**Comment by dlabun** [comment]
Since there's a generic problem with I2C on the nRF52 the fix should be generic to all of the nRF52 boards and not just target a single board.

**Comment by gtalusan** [comment]
You're right.  No worries, I'll just leave this in my fork now.

**Pull request closed without merging**
