### PR TITLE
Support for Hardware Number Generator

### PR DESCRIPTION
**Pull request by d00616**
This is an enhancement of https://github.com/sirleech/TrueRandom to nRF5 platform.

Contents:
- Support for nRF5 and avr platform
- New README.md, replaces readme
- Fixed Example AllFunctions
- Build library in .travis.yaml for nRF51 and nRF52

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Hi @d00616,

Thanks for submitting this. Is there any reason you didn't submit a pull request to the original TrueRandom repo?

I'm not too keen about bundling this library with the core. The official Arduino cores usually just have `SPI`, `Wire`, `SoftwareSerial`. Then the rest are installable via the library manager, I've taken a similar approach with my `BLEPeripheral` library.

**Comment by d00616** [comment]
Hello @sandeepmistry,

i have opened a pull request to the original library. This library isn't listed in library manager. So nobody can find this.

I like the Teensy way. The installer asks what Libraries, optimized for Teensy, have to installed. Whats about an Arduino Menu to install optimzed Libraries?

**Comment by sandeepmistry** [comment]
> Whats about an Arduino Menu to install optimzed Libraries?

Not something I plan to work on. However, I'm open to adding links to the read me for "recommended" libraries.

**Comment by sandeepmistry** [comment]
I'm going to close this for now, since there's an upstream PR: https://github.com/sirleech/TrueRandom/pull/1

If the original author does not merge, you can always consider renaming the library and ask the Arduino team to add the renamed library to the library manager.

**Pull request closed without merging**
