### PR TITLE
Update compatibility mode for different F_CPU values

### PR DESCRIPTION
**Pull request by nsamala**
Title says it all. Let me know what you think! This useful for boards like the nRF52832 where the boards are set to run at 64 MHz

### CODE REVIEW

**Comment by dlabun** [comment]
That's old compatibility code that nobody should be using now a days.... Do you have a use case for changing it?

**Comment by nsamala** [comment]
@dbalun literally just for some test cases to pass for merging https://github.com/nsamala/platform-nordicnrf52/tree/feather_nrf52832 into PlatformIO

**Comment by dlabun** [comment]
I'm going to leave this one for Sandeep to make the final call on, I am not of the opinion that we should be making changes to accommodate PlatformIO.

**Comment by nsamala** [comment]
@dlabun the existing compatibility mode won't change. This just ensures that you don't hardcode the F_CPU into build files (which is what the maintainers of the PIO library had done) for this code to work. This is applicable outside of PlatformIO as well.

**Pull request merged**
