### PR TITLE
added tools.openocd.upload.network_pattern for ArduinoOTA

### PR DESCRIPTION
**Pull request by jandrassy**
support for [ArduinoOTA library](https://github.com/jandrassy/ArduinoOTA)

### CODE REVIEW

**Comment by jandrassy** [comment]
strange question. you can connect Ethernet or WiFi module to nRF5 like to any other MCU with SPI or Serial interface. I have an Arch Link board with nRF51 and Wiznet 5500 on board

**Comment by dlabun** [comment]
Not strange question, I didn't know if the assumption was just like you said or if this was targeting a specific board only. Would you mind updating the readme file as well to include a link to the appropriate version of the OTA library?

**Comment by jandrassy** [comment]
README in the root of the repo? it doesn't mention any libraries except of the native BLE library.

**Comment by jandrassy** [comment]
> 
> 
> Yes please. Until now we've been discouraging any reliance on or inclusion of external libraries which is why the BLE library is the only one mentioned in the readme.

why not leaving it that way. someone who needs the remote upload will find the Arduino OTA library. only with this PR they do not need to patch platform.txt with lines, which are out-of-the-box in platform.txt of many other cores

**Comment by jandrassy** [comment]
please merge it, so I can remove the instructions to add this two lines from the ArduinoOTA library README. the two lines do nothing, until someone uses the ArduinoOTA library. (It is allready in Library Manager)

**Comment by dlabun** [comment]
Closing, changes requested never made.

**Comment by jandrassy** [comment]
@sandeepmistry, I made this pull request with two lines copied from Arduino SAMD package platform.txt for network upload to support the ArduinoOTA library. The ArduinoOTA library is a modification of your WiFi101OTA library. The modification supports different network libraries and support more types of MCU. The support of nRF5 is your code for SAMD rewritten for the registry names of nRF5. I don't understand why this two lines can't be merged. Basically it is your work, I only ported it to nRF5.

**Comment by dlabun** [comment]
It was closed because you were asked 6 months ago to update read me file with a link to the appropriate OTA library. Without it, how is anyone supposed to know about this feature?

**Comment by jandrassy** [comment]
@sandeepmistry Hello Sandeep, I see you maintain this core again. please reconsider this PR

**Pull request closed without merging**
