### PR TITLE
Identify analogRead() input type and set right pin

### PR DESCRIPTION
**Pull request by carlosperate**
This first commit is only for the micro:bit board, but it is meant to be a starting point to agree on the correct implementation and then extend it to the rest of the variants.

A description of the problem can be found in https://github.com/sandeepmistry/arduino-nRF5/issues/133 and this initial solution was described in the comment https://github.com/sandeepmistry/arduino-nRF5/issues/133#issuecomment-293106851.

### CODE REVIEW

**Comment by carlosperate** [comment]
Btw, the main reason I haven't named the function `analogInputToDigitalPin()` as done in the AVR core macro ([GitHub/Arduino/hardware/arduino/avr/variants/standard/pins_arduino.h#L30](https://github.com/arduino/Arduino/blob/89e3c5290f4fc95db4159f348d6b4e326d415e64/hardware/arduino/avr/variants/standard/pins_arduino.h#L30)) is because the macro returns `-1` for non-valid inputs, and since all the types involved here are unsigned I though it would be easier to follow without casting.
Nevertheless signed to unsigned conversion is well-defined, and casting `-1` (not matter the size) to uint32 would result in `0xFFFFFFFF`, and also cause the same early exit when `(ulPin >= PINS_COUNT)`.

Not sure if it's better to keep it as it is, or change it to `analogInputToDigitalPin()`.

**Comment by sandeepmistry** [comment]
@carlosperate nice!

I would prefer using `analogInputToDigitalPin`. I'm open to making all the pin mapping arrays in the variants to signed if it helps.

**Comment by carlosperate** [comment]
Yeah, after reading my previous message again I think it is better to use `analogInputToDigitalPin()`. If the SAMD core version of `analogRead` has unsigned integers in its signature I think it's fine keeping it as it is. I'll explicitly add the cast to the return value so that it's clear a `-1` would end up as `0xFFFFFFFF`, and it we'll be good to go.

**Comment by carlosperate** [comment]
Damn, so looking at it again I've changed my mind once more and there are a couple of issues I didn't originally realised.

Okay, the first thing is that, as it currently stands, the `_analogChannelPin()` inline function from this PR should perhaps stay with that (or similar) name instead of using `analogInputToDigitalPin` because it does a bit more than what the `analogInputToDigitalPin()` macro does.
For each "ADC channel" value (i.e. 0 to 5 in an Arduino Uno) it returns the equivalent digital pin, so that's the same; but it also returns a valid digital pin for an input value that corresponds to a valid analog pin (so in this case for the micro:bit pin 10 is ADC channel 5, and so `_analogChannelPin(10)` does returns `10` instead of `-1`).

The other thing is that, if the "digital pin value" for an an "ADC pin" overlaps with the ADC channel range (so let's say ADC channel 0 to 5 are digital pins 2 to 7) then there is no way to detect when the input argument is supposed to represent the channel vs. when it is meant to represent the digital input value.

So depending on the implementation the following loop could give unexpected results:
```c
#define PIN_A0               (2)
#define PIN_A1               (3)
#define PIN_A2               (4)
#define PIN_A3               (5)
#define PIN_A4               (6)
#define PIN_A5               (7)
#define NUM_ANALOG_INPUTS    (6u)

for (size_t i = 0; i < NUM_ANALOG_INPUTS; i++) {
  Serial.println(_analogChannelPin(i))
}
```

For the following lookup table, which prioritises channels, we would give the result below:

```c

_analogChannelPin(uint32_t pin) {
  switch (pin) {
    case 0:  return PIN_A0;
    case 1:  return PIN_A1;
    case 2:  return PIN_A2;
    case 3:  return PIN_A3;
    case 4:  return PIN_A4;
    case 5:  return PIN_A5;
    case PIN_A4: return PIN_A4;
    case PIN_A5: return PIN_A5;
    // Otherwise non-analog pin so return out of range pin to exit early
    default: return PINS_COUNT;
  }
}
```

```
2
3
4
5
6
7
```
This result makes sense in this loop, but if a board has pins "2, 3, 4, 5, 6 and 7" marked as ADC, you would expect the function call to be `analogRead(7)` instead of `analogRead(5)`.

On the other hand, the following lookup table prioritising digital pin values would give the following confusing result:

```c
_analogChannelPin(uint32_t pin) {
  switch (pin) {
    case 0:  return PIN_A0;
    case 1:  return PIN_A1;
    case PIN_A0:  return PIN_A0;
    case PIN_A1:  return PIN_A1;
    case PIN_A2:  return PIN_A2;
    case PIN_A3:  return PIN_A3;
    case PIN_A4:  return PIN_A4;
    case PIN_A5:  return PIN_A5;
    // Otherwise non-analog pin so return out of range pin to exit early
    default: return PINS_COUNT;
  }
}
``` 

```
2
3
2
3
4
5
```

**Comment by sandeepmistry** [comment]
Hmm, maybe we're thinking too much about this. Some nRF5x boards are not really intended for Arduino users (like they don't have label Ax pins in the right spot or sequential). What if we just add this functionality for the ones that are based on boards like the Uno etc, where the Ax pins are all sequential?

**Comment by carlosperate** [comment]
I think you are right there, if a board has both "pin numbering" and "Ax" numbers, then the manufacturer is most likely following the Arduino pin conventions. In that case the analogRead() function should accept both types of inputs. Otherwise, if the board doesn't have Ax pin number then the analogRead() function should consider its input to be only in the "generic pin number" format.

**Comment by sandeepmistry** [comment]
@carlosperate ok, so back to something like https://github.com/sandeepmistry/arduino-nRF5/issues/133#issuecomment-293104322 then?

**Comment by sandeepmistry** [comment]
Closing this for now due to lack of activity. Please let us know if/when this is ready for review and testing.

**Pull request closed without merging**
