### PR TITLE
Bugfix169 analog write

### PR DESCRIPTION
**Pull request by micooke**
* Fix bug #169
* wiring_analog_* : fallback to digitalWrite if no available PWM channel (copied from AVR core)
* wiring_analog_nRF52.c : convert pwmChannelPins & pwmChannelSequence -> pwmContext to semi-standardise pwm pin allocation and pwm status between nRF51 and nRF52
* wiring_private.h : Move pwm structures defines out of wiring_analog_* into wiring_private and make the instantiation of these structure externs instead of statics
* wiring_digital.c : disable the appropriate pwm timer when a digitalWrite is sent to an allocated (from analogWrite) pwm pin, and free up the pwm channel for re-allocation

### CODE REVIEW

**Comment by dlabun** [comment]
This PR has a bunch of stuff related to adding the BMP... Can remove those commits from this PR so I can merge it? Not a GitHub expert...

**Comment by micooke** [comment]
Oh sorry about that. I mustn't have rebased it properly - ill try and fix it today.

**Comment by micooke** [comment]
What a mess, this is because i (stupidly) made the BMP changes to my trunk

**Comment by dlabun** [comment]
No worries. If its easier you could always just do a new PR.

**Comment by micooke** [comment]
What do you see on you end post a PR? Do you get all my intermittent garbage logs and changes or just a unified change? If you get all the garbage ill redo both (and try to make it neater next time). 
Otherwise ill give it one go and if it doesnt work ill redo them

**Comment by dlabun** [comment]
I can see that there's been 7 commits to this PR with all of the individual changes per commit. I was hoping there was a way to just approve the last commit...either I can't find that button or it doesn't exist.

**Comment by jeremypoulter** [comment]
You can use git cherrypick to merge specific commits on to a new branch and
then change to edit the PR to point at the new branch I think (or just
create a new PR)

Jeremy

**Pull request closed without merging**
