### PR TITLE
Add PCA1000X variant PCA10001

### PR DESCRIPTION
**Pull request by oyooyo**
This PR adds a PCA1000X board variant called PCA10001, for the PCA10001 development board.

### CODE REVIEW

**Comment by dlabun** [comment]
@sandeepmistry Should the PCA10001 be broken out to a separate folder?

**Comment by sandeepmistry** [comment]
@dlabun no I think it's ok, it's a sub-variant of PCA1000x.

@oyooyo please see comment in https://github.com/sandeepmistry/arduino-nRF5/pull/224#issuecomment-357523445 . Do you want us to merge this or PR #224, which has both changes?

**Comment by oyooyo** [comment]
@sandeepmistry Oops, sorry for that - I actually intended to truly separate the changes in this PR and PR #224, but I guess I screwed up (I'm still severely struggling with mastering GIT and Github).

I'll update both PRs later today to address the mentioned issues.

**Comment by oyooyo** [comment]
Ok, I think I managed to add the missing Travis CI entry to this PR.
Unfortunately I still haven't figured out how to properly remove the duplicate commit 29e5058 from PR #224, sorry :-(

**Comment by dlabun** [comment]
No worries, i'm no Github expert... If you need to you can simply create a new PR.

**Comment by oyooyo** [comment]
I believe both PRs (#224 and #226) should be okay now.

**Pull request merged**
