### PR TITLE
Support standard reset button as default.

### PR DESCRIPTION
**Pull request by bojh**
Nordic does provide a standard mapping of a reset functionality on GPIO pin P.21 which is in most boards the reset button. To support the RESET button in a standard Arduino way, we have to provide a C compile flag CONFIG_GPIO_AS_PINRESET.

### CODE REVIEW

**Comment by dlabun** [comment]
Is there an issue with the reset button currently? This is just my lack of understand of the change...

**Comment by sandeepmistry** [comment]
@bojh cool, I didn't know about this feature!

@dlabun take a look in the `SystemInit` function in  [cores/nRF5/SDK/components/toolchain/system_nrf52.c](https://github.com/sandeepmistry/arduino-nRF5/blob/dc53980c8bac27898fca90d8ecb268e11111edc1/cores/nRF5/SDK/components/toolchain/system_nrf52.c#L153-L169)

```c
/* Configure GPIO pads as pPin Reset pin if Pin Reset capabilities desired. If CONFIG_GPIO_AS_PINRESET is not
      defined, pin reset will not be available. One GPIO (see Product Specification to see which one) will then be
      reserved for PinReset and not available as normal GPIO. */
    #if defined (CONFIG_GPIO_AS_PINRESET)
        if (((NRF_UICR->PSELRESET[0] & UICR_PSELRESET_CONNECT_Msk) != (UICR_PSELRESET_CONNECT_Connected << UICR_PSELRESET_CONNECT_Pos)) ||
            ((NRF_UICR->PSELRESET[1] & UICR_PSELRESET_CONNECT_Msk) != (UICR_PSELRESET_CONNECT_Connected << UICR_PSELRESET_CONNECT_Pos))){
            NRF_NVMC->CONFIG = NVMC_CONFIG_WEN_Wen << NVMC_CONFIG_WEN_Pos;
            while (NRF_NVMC->READY == NVMC_READY_READY_Busy){}
            NRF_UICR->PSELRESET[0] = 21;
            while (NRF_NVMC->READY == NVMC_READY_READY_Busy){}
            NRF_UICR->PSELRESET[1] = 21;
            while (NRF_NVMC->READY == NVMC_READY_READY_Busy){}
            NRF_NVMC->CONFIG = NVMC_CONFIG_WEN_Ren << NVMC_CONFIG_WEN_Pos;
            while (NRF_NVMC->READY == NVMC_READY_READY_Busy){}
            NVIC_SystemReset();
        }
    #endif
```

I'm wondering if we should set the define per variant instead, just in case some boards need to use pin 21 has a regular GPIO. Thoughts?

**Comment by dlabun** [comment]
Setting the reset pin per variant makes alot of sense, it'll keep the core flexible for future boards.

**Comment by bojh** [comment]
@dlabun perhabs it would have been a better idea to discuss this first as an issue - you are right.
Mainly I'am working with the nordic 52 DK board for testing and was wondering why it was not functional just it the phase I need a dedicated embedded HW. 
For me it would also be a good approach to bind that feature to variants where the HW is known and P0.21 is directly used as RESET Button. So people are then aware to configure it as needed.

**Comment by dlabun** [comment]
@bojh No no, this was just me not realizing the reset pin was configurable. Personally my designs don't involve reset buttons so it never crossed my mind

**Comment by sandeepmistry** [comment]
Ok, so what do we think about having an optional `PIN_RESET` define in `variant.h` then in the `init()` function in `cores/nRF5/wiring.c` when can have some similar code to the Nordic one?

Could someone test if something other the pin 21 can be used to reset a nRF52DK?

**Comment by dlabun** [comment]
I test it on my board but I probably won't have time until Friday.

**Comment by sandeepmistry** [comment]
@dlabun did you get a chance to try this out? Maybe another one to get in for #182?

**Comment by dlabun** [comment]
@sandeepmistry No, forgot all about this one. I'll try to test it next week when my schedule frees up.

**Comment by micooke** [comment]
The reset pin is normally mapped to PO.21 (it is on the Taida board), but it can be remapped to pretty much anything using NRF_UICR->PSELRESET[0] = pin, or NRF_UICR->PSELRESET[1] = pin. This is separate to enabling the pin reset though, and should be able to be a static in the variant.h.

**Comment by micooke** [comment]
It looks like assignment of the gpio for pin reset has to happen at compile time.
I tried a re-assignment in a sketch .ino, based off this nfc to gpio example, which resulted in a bootloop.

To explain this NVIC_SystemReset() needs to be called to enable the changes in NVMC, however the changes dont seem to stick and i get in a bootloop. The Adafruit example attempts to execute the code for when CONFIG_NFCT_PINS_AS_GPIOS is defined.

https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/Bluefruit52Lib/examples/Hardware/nfc_to_gpio/nfc_to_gpio.ino

``` c++
if (NRF_UICR->PSELRESET[1] != PIN_BUTTON1)
  {
    NRF_NVMC->CONFIG = NVMC_CONFIG_WEN_Wen << NVMC_CONFIG_WEN_Pos;
    while (NRF_NVMC->READY == NVMC_READY_READY_Busy);
    NRF_UICR->PSELRESET[1] = PIN_BUTTON1; // TEMP
    while (NRF_NVMC->READY == NVMC_READY_READY_Busy);
    NRF_NVMC->CONFIG = NVMC_CONFIG_WEN_Ren << NVMC_CONFIG_WEN_Pos;
    while (NRF_NVMC->READY == NVMC_READY_READY_Busy);
    
    Serial.println("PIN RESET SET TO PO.04");
    delay(3000);
    NVIC_SystemReset();
  }
```

**Comment by ntavish** [comment]
One way to do this outside of the core is to use `initVariant()`, which is defined as `void initVariant() __attribute__((weak));` and called before `setup()` in `main()`. That way we do not need the `CONFIG_GPIO_AS_PINRESET` define for compiling core, and can have variant set reset pin. I'll try to test this.

**Comment by ntavish** [comment]
Please see https://github.com/sandeepmistry/arduino-nRF5/pull/212 

This works if there is RESET_PIN defined in `variant.h`:
```
// 21 is not from g_ADigitalPinMap, but nrf P0.21
#define RESET_PIN            21
```

**Comment by sandeepmistry** [comment]
@bojh could you please update this PR or make a new one to add the changes @ntavish described above for the specific boards with reset pins. PR #212 has been merged, so the variant just needs a `#define RESET_PIN            21` in the variant header file.

**Comment by bojh** [comment]
Hi @sandeepmistry ,
I have checked up following nRF52 based platforms: RB Blend 2, RB Nano 2, Taida century NRF52 miniboard, Eclectronut tabs bluey & hackaBLE and Generic (nRF52). They all provide a Reset button/port linked to the nRF52x chip P0.21 GPIO. If it's OK, I can provide a new PR with modified variant.h header files with the `#define RESET_PIN 21` statement.

**Comment by micooke** [comment]
My 2 cents on this is that i use the generic boards for development, with a specific board in mind as the end product.

Sometimes ill need 2 buttons, other times ill prefer to have the pin reset functionality. Hence why i proposed PR #208 using the generic nRF52832 as an example

**Comment by sandeepmistry** [comment]
@bojh please proceed with your proposal from https://github.com/sandeepmistry/arduino-nRF5/pull/91#issuecomment-355980886.

I'm closing this pull request for now.

**Comment by drmpf** [comment]
setting #define RESET_PIN 21  for NanoV2 did not work for me.
Perhaps there also needs to be mods to the linker similar to 
NFC pins as GPIO #155

**Pull request closed without merging**
