### PR TITLE
Added decaWave DWM1001-DEV board

### PR DESCRIPTION
**Pull request by Beetix**
Hi,

I have added support for decaWave DWM1001-DEV board. I am not working for decaWave so this is an **unofficial** port. I have tried to optimize the pinout based on the available pins. [Here](https://github.com/sandeepmistry/arduino-nRF5/files/2495097/dwm1001-dev_arduino_pinout.pdf) is a document explaining the pinout.

It would be great if you could merge it.

Thanks

### CODE REVIEW

**Comment by dlabun** [comment]
Have you tested this on real hardware? I don't have access to this board so I can't verify if it works.

**Comment by Beetix** [comment]
Yes, although not exhaustively. I have tested the LEDs, the internal SPI
(SPI1), the serial and the Bluetooth with the softdevice s132 (ran serial
example from BLEPeripheral library).

**Comment by Beetix** [comment]
2 GPIOs on the DWM1001 are not attached to the nRF52 so I removed them. I had to shift the digital pins. [Here](https://github.com/sandeepmistry/arduino-nRF5/files/2557737/dwm1001-dev_arduino_pinout.pdf) is the new pinout. I have written a small sketch that I ran on the board to test the GPIOs:
```c++
void digitalOutputTest(int pin) {
  Serial.print("Pin ");
  Serial.print(pin);
  Serial.println(" low");
  digitalWrite(pin, LOW);
  delay(1000);
  Serial.print("Pin ");
  Serial.print(pin);
  Serial.println(" high");
  digitalWrite(pin, HIGH);
}

void setup() {
  // Digital pins
  for (int pin = 0; pin < NUM_DIGITAL_PINS; pin++)
  {
    pinMode(pin, OUTPUT);
    digitalWrite(pin, HIGH);
  }

  // LEDs
  pinMode(LED_BUILTIN, OUTPUT);
  pinMode(LED_GREEN, OUTPUT);
  pinMode(LED_BLUE, OUTPUT);

  digitalWrite(LED_BUILTIN, HIGH);
  digitalWrite(LED_GREEN, HIGH);
  digitalWrite(LED_BLUE, HIGH);

  // Button
  pinMode(BTN, INPUT_PULLUP);
  
  Serial.begin(115200);
}

void loop() {
  Serial.println("DWM1001-DEV Test");
  // Button
  Serial.println("Please press button to start");
  while (digitalRead(BTN) == HIGH);

  // Digital pins
  for (int pin = 0; pin < NUM_DIGITAL_PINS; pin++)
  {
    digitalOutputTest(pin);
  }

  // LEDs
  digitalOutputTest(LED_BUILTIN);
  digitalOutputTest(LED_GREEN);
  digitalOutputTest(LED_BLUE);

  Serial.println("Finished test");
}
```

**Comment by dlabun** [comment]
Cool, I’ll merge it in soon.

**Comment by Beetix** [comment]
Great, thanks.

**Pull request merged**
