### PR TITLE
Use GPIO_PIN_CNF_DRIVE_S0D1 for Wire lib pin configurations

### PR DESCRIPTION
**Pull request by sandeepmistry**
As discussed in #93.

cc/ @maker-ja @dlabun

### CODE REVIEW

**Comment by dlabun** [comment]
@sandeepmistry I tested this on my board and it worked as well, want me to merge it?

**Comment by sandeepmistry** [comment]
Thanks for testing it out, yes please merge :)

**Comment by sandeepmistry** [comment]
I'll aim to make a new release after this and #100 are merged.

**Comment by dlabun** [comment]
Both are merged now, Once v0.3 is released I'll do a PR for a changelog.

**Pull request merged**
